EXDIBO/Controllers/ExpedienteController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;

namespace EXDIBO.Controllers
{
   public class ExpedienteController : Controller
    {

        [Authorize(Roles = "0,1,2,3,4,5,6,7,8,9")]
        public IActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = "0,1,2,3,4,5,6,7,8,9")]
        public IActionResult Portada()
        {
            return View();
        }

        [Authorize(Roles = "0,1,2,3,4,5,6,7,8,9")]
        public IActionResult ProblemasConexion()
        {
            return View();
        }

        [Authorize(Roles = "0,1,2,3,4,5,6,7,8,9")]
        public IActionResult AccesoDenegado()
        {
            return View();
        }

        [Authorize(Roles = "0,1,2,3,4,5,6,7,8,9")]
        public IActionResult Politicas()
        {
            return View();
        }

        [Authorize(Roles = "0,1,2,3,4,5,6,7,8,9")]
        public IActionResult Error404()
        {
            return View();
        }

        public IActionResult PoliticasPublicas()
        {
            return View();
        }

        public IActionResult AccesoNegado()
        {
            return View();
        }

        public IActionResult EXDIBO()
        {
            return View();
        }
    }
}

EXDIBO/Controllers/FincaController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using EXDIBO.Models;
using EXDIBO.Util;

namespace EXDIBO.Controllers
{
    public class FincaController : Controller
    {
        [Authorize(Roles = "0,1,2,3,4,5,6,7,8,9")]
        public IActionResult Fincas()
        {
            List<Farm> farms = new ServiceFarm().GetAllFarm();
            return View(farms);
        }

        [Authorize(Roles = "0,1,2,3,4,5,6,7,8,9")]
        public IActionResult Grupos()
        {
            List<Group> groups = new ServiceFarm().GetAllGroup();
            return View(groups);
        }
    }
}

EXDIBO/Controllers/ReporteController.cs
using Microsoft.AspNetCore.Mvc;
using EXDIBO.Util;
using Microsoft.AspNetCore.Authorization;
using EXDIBO.Models;

namespace EXDIBO.Controllers
{
    public class ReporteController : Controller
    {

        [Authorize(Roles = "0,1,2,3,4,5,6,7,8,9")]
        public IActionResult Gestacion()
        {
            try
            {
                return View();
            }
            catch (Exception) 
            {
                return RedirectToAction("ProblemasConexion", "Expediente");
            }
        }

        [Authorize(Roles = "0,1,2,3,4,5,6,7,8,9")]
        [HttpGet]
        public JsonResult DataGestacion()
        {
            try
            {
                DateTime hasta = DateTime.Now;
                DateTime desde = new(hasta.Year - 1, hasta.Month, 01, 00, 00, 00);
                Serie data = new ServiceReport().GetPregnancy(desde, hasta);
                return Json(data);
            }
            catch (Exception)
            {
                Gestacion();
                return Json(null);
            }
        }

        [Authorize(Roles = "0,1,2,3,4,5,6,7,8,9")]
        public IActionResult PrenesEfectiva()
        {
            ViewData["error"] = String.Empty;
            return View(null);
        }

        [Authorize(Roles = "0,1,2,3,4,5,6,7,8,9")]
        [HttpPost]
        public IActionResult PrenesEfectiva(DateTime Desde, DateTime Hasta)
        {

            try
            {
                ViewData["error"] = String.Empty;

                if (DateTime.Compare(Hasta, DateTime.Now) > 0)
                {
                    ViewData["error"] = "La Fecha debe no debe ser mayor a hoy";
                    return View(null);
                }
                else if (DateTime.Compare(Desde, Hasta) > 0)
                {
                    ViewData["error"] = "La Fecha de Inicio debe ser menor a la Fecha Final";
                    return View(null);
                }
                else if (DateTime.Compare(Desde, new DateTime(0001, 1, 1, 00, 00, 00)) == 0)
                {
                    ViewData["error"] = "Debe indicar una fecha para Desde valida";
                    return View(null);
                }
                else if (DateTime.Compare(Hasta, new DateTime(0001, 1, 1, 00, 00, 00)) == 0)
                {
                    ViewData["error"] = "Debe indicar una fecha para Hasta valida";
                    return View(null);
                }

                List<PregnantReport> report = new ServiceReport().PregnantReport(Desde, Hasta);
                if (report.Count() <= 0)
                {
                    ViewData["error"] = String.Empty;
                    report = null;
                }
                return View(report);
            }
            catch (Exception)
            {
                return RedirectToAction("ProblemasConexion", "Expediente");
            }
        }


        [Authorize(Roles = "0,1,2,3,4,5,6,7,8,9")]
        public IActionResult Nacimientos()
        {
            ViewData["error"] = String.Empty;
            return View(null);
        }


        [Authorize(Roles = "0,1,2,3,4,5,6,7,8,9")]
        [HttpPost]
        public IActionResult Nacimientos(DateTime Desde, DateTime Hasta)
        {
            try
            {
                ViewData["error"] = String.Empty;

                if (DateTime.Compare(Hasta, DateTime.Now) > 0)
                {
                    ViewData["error"] = "La Fecha debe no debe ser mayor a hoy";
                    return View(null);
                }
                else if (DateTime.Compare(Desde, Hasta) > 0)
                {
                    ViewData["error"] = "La Fecha de Inicio debe ser menor a la Fecha Final";
                    return View(null);
                }
                else if (DateTime.Compare(Desde, new DateTime(0001, 1, 1, 00, 00, 00)) == 0)
                {
                    ViewData["error"] = "Debe indicar una fecha para Desde valida";
                    return View(null);
                }
                else if (DateTime.Compare(Hasta, new DateTime(0001, 1, 1, 00, 00, 00)) == 0)
                {
                    ViewData["error"] = "Debe indicar una fecha para Hasta valida";
                    return View(null);
                }
                List<BovineReport> report = new ServiceReport().BornReport(Desde, Hasta);
                if (report.Count() <= 0)
                {
                    ViewData["error"] = String.Empty;
                    report = null;
                }
                return View(report);
            }
            catch (Exception)
            {
                return RedirectToAction("ProblemasConexion", "Expediente");
            }
        }


        [Authorize(Roles = "0,1,2,3,4,5,6,7,8,9")]
        public IActionResult AnimalDesecho()
        {
            ViewData["error"] = String.Empty;
            return View(null);
        }

        [Authorize(Roles = "0,1,2,3,4,5,6,7,8,9")]
        [HttpPost]
        public IActionResult AnimalDesecho(DateTime Desde, DateTime Hasta)
        {
            try
            {
                ViewData["error"] = String.Empty;

                if (DateTime.Compare(Hasta, DateTime.Now) > 0)
                {
                    ViewData["error"] = "La Fecha debe no debe ser mayor a hoy";
                    return View(null);
                }
                else if (DateTime.Compare(Desde, Hasta) > 0)
                {
                    ViewData["error"] = "La Fecha de Inicio debe ser menor a la Fecha Final";
                    return View(null);
                }
                else if (DateTime.Compare(Desde, new DateTime(0001, 1, 1, 00, 00, 00)) == 0)
                {
                    ViewData["error"] = "Debe indicar una fecha para Desde valida";
                    return View(null);
                }
                else if (DateTime.Compare(Hasta, new DateTime(0001, 1, 1, 00, 00, 00)) == 0)
                {
                    ViewData["error"] = "Debe indicar una fecha para Hasta valida";
                    return View(null);
                }
                List<Bovine> report = new ServiceReport().DiscardReport(Desde, Hasta);
                if (report.Count() <= 0)
                {
                    ViewData["error"] = String.Empty;
                    report = null;
                }
                return View(report);
            }
            catch (Exception)
            {
                return RedirectToAction("ProblemasConexion", "Expediente");
            }
        }



        [Authorize(Roles = "0,1,2,3,4,5,6,7,8,9")]
        public IActionResult Inyectados()
        {
            ViewData["error"] = String.Empty;
            return View(null);
        }

        [Authorize(Roles = "0,1,2,3,4,5,6,7,8,9")]
        [HttpPost]
        public IActionResult Inyectados(DateTime Desde, DateTime Hasta)
        {
            try
            {
                ViewData["error"] = String.Empty;

                if (DateTime.Compare(Hasta, DateTime.Now) > 0)
                {
                    ViewData["error"] = "La Fecha debe no debe ser mayor a hoy";
                    return View(null);
                }
                else if (DateTime.Compare(Desde, Hasta) > 0)
                {
                    ViewData["error"] = "La Fecha de Inicio debe ser menor a la Fecha Final";
                    return View(null);
                }
                else if (DateTime.Compare(Desde, new DateTime(0001, 1, 1, 00, 00, 00)) == 0)
                {
                    ViewData["error"] = "Debe indicar una fecha para Desde valida";
                    return View(null);
                }
                else if (DateTime.Compare(Hasta, new DateTime(0001, 1, 1, 00, 00, 00)) == 0)
                {
                    ViewData["error"] = "Debe indicar una fecha para Hasta valida";
                    return View(null);
                }
                List<WithdrawalReport> report = new ServiceReport().WithdrawalReport(Desde, Hasta);
                if (report.Count() <= 0)
                {
                    ViewData["error"] = String.Empty;
                    report = null;
                }
                return View(report);
            }
            catch (Exception)
            {
                return RedirectToAction("ProblemasConexion", "Expediente");
            }
        }

        [Authorize(Roles = "0,1,2,3,4,5,6,7,8,9")]
        public IActionResult Implantado()
        {
            ViewData["error"] = String.Empty;
            return View(null);
        }

        [Authorize(Roles = "0,1,2,3,4,5,6,7,8,9")]
        [HttpPost]
        public IActionResult Implantado(DateTime Desde, DateTime Hasta)
        {
            try
            {
                ViewData["error"] = String.Empty;

                if (DateTime.Compare(Hasta, DateTime.Now) > 0)
                {
                    ViewData["error"] = "La Fecha debe no debe ser mayor a hoy";
                    return View(null);
                }
                else if (DateTime.Compare(Desde, Hasta) > 0)
                {
                    ViewData["error"] = "La Fecha de Inicio debe ser menor a la Fecha Final";
                    return View(null);
                }
                else if (DateTime.Compare(Desde, new DateTime(0001, 1, 1, 00, 00, 00)) == 0)
                {
                    ViewData["error"] = "Debe indicar una fecha para Desde valida";
                    return View(null);
                }
                else if (DateTime.Compare(Hasta, new DateTime(0001, 1, 1, 00, 00, 00)) == 0)
                {
                    ViewData["error"] = "Debe indicar una fecha para Hasta valida";
                    return View(null);
                }
                List<WithdrawalReport> report = new ServiceReport().ImplantReport(Desde, Hasta);
                if (report.Count() <= 0)
                {

EXDIBO/Views/Expediente/AccesoDenegado.cshtml
@{
    ViewData["Title"] = "Acceso Denegado";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="text-center mt-4">

<h1 class="mt-4 display-3">Acceso Denegado</h1>


<h3 class="mt-3">Este usuario no se encuentra autorizado para ingresar a esta opcion de la aplicación</h3>


 <a class="btn btn-lg btn-success mt-4 text-dark" asp-area="" asp-controller="Expediente" asp-action="Portada"><i class="fa-solid fa-bars"></i> Menú</a>

 </div>

EXDIBO/Views/Expediente/AccesoNegado.cshtml
@{
    ViewData["Title"] = "Acceso Denegado";
    Layout = "~/Views/Shared/_Start.cshtml";
}
<div class="text-center">

<h1>Acceso Denegado</h1>

<h3>Este usuario no se encuentra autorizado para ingresar a la aplicación</h3>

<h4> @ViewData["ErrorInicio"]</h4>

<a asp-controller="Usuario" asp-action="IniciarSesion"> Iniciar Sesi&oacute;n </a>

</div>

EXDIBO/Views/Expediente/EXDIBO.cshtml
@{
    ViewData["Title"] = "Bienvenid@s";
    Layout = "~/Views/Shared/_Start.cshtml";
}


<div class="text-center">
    <h1 class="display-5">Bienvenid@@s</h1>
    <h5 class="display-1 text-center" style="font-family:'Liberation Sans'">Expediente Digital Bovino</h5>
    <div class="container">
        <p>
            ¡Bienvenid@s a la Aplicación Web del Expediente Digital Bovino, esta aplicación se inicio desde el pasado 1 de Mayo de 2022 y con la meta de finalizar la III Etapa en Noviembre 2022!<br />
            Espero que les guste sea de su agrado y lo más importante sea de máxima utlidad con la accesibilidad que cuesta esta aplicación.<br />
            Para mi es un gran logro, poner en servicio esta aplicación, aceptando las críticas de mi dos asesores de la finca Don Ovidio y Doña Blanca que son dos finqueros que me asesoran en la conformación de esta aplicación. Acá les damos una breve introducción.
        </p>
        <p>
            EXDIBO les da la bienvenida a su nueva página web, en la que podrá acceder a todos nuestros servicios y gozar de estos de una forma fácil y rápida y con un solo clic.<br />
            Soy un profesional en la solución de problemas, y la solvencia al problema es esta aplicación web, desarrollada y realizada por el Ingeniero Andrew Anchía González dando estos acabados a la Interfaz de usuario muy limpia y descriptiva para usuario con poco conocimiento en el ambiente tecnológico.<br />
            Otro punto es la accesibilidad al Expediente Digital Bovino que los usuarios estando a nivel nacional como internacional puedan acceder a su información, disponiendo de las últimas tecnologías disponibles en campo tecnologico para proporcionar las últimas y mejores tendencias en cuanto a calidad, seguridad y disponibilidad.<br />
            Así, que espero que todos los usuarios pueden disfrutar de esta aplicación web nueva y que les proporcione un servicio completo del registro y análisis de la información almacenada, ya que podemos acceder al expediente rápidamente, establecer nuevos registros, ver los últimos registros realizados o editar alguno de estos.<br />
            Todos los usuarios, pueden conectarse a la aplicación web a través del internet esta nueva sede online que nos permite acceder y dar una respuesta de manera fácil y rápida a todos los usuarios.<br />
            En EXDIBO, somos conscientes de la importancia de estar en constante aseguramiento del servicio y brindar el mejor servicio a nuestros usuarios
            También se pueden realizar solicitudes de cálculo o reportes y resolver cualquier tipo de duda respecto a las decisiones posibles a tomar según lo visto en los reportes y contar con estas herramientas le permite a la finca un mejor rendimiento y toma de decisiones en el manejo de sus animales, recursos, medicamentos o tiempos de retiro.<br />
        </p>
    </div>
</div>

EXDIBO/Views/Expediente/Index.cshtml
@{
    ViewData["Title"] = "Bienvenid@s";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="text-center">
    <h1 class="display-5">Bienvenid@@s</h1>
    <h5 class="display-1 text-center" style="font-family:'Liberation Sans'">Expediente Digital Bovino</h5>
    <div class="container">
        <p>
            ¡Bienvenid@s a la Aplicación Web del Expediente Digital Bovino, esta aplicación se inicio desde el pasado 1 de Mayo de 2022 y con la meta de finalizar en Noviembre 2022!<br />
            Espero que les guste sea de su agrado y lo más importante sea de máxima utlidad con la accesibilidad que cuesta esta aplicación.<br />
            Para mi es un gran logro, poner en servicio esta aplicación, aceptando las críticas de mi dos asesores de la finca Don Ovidio y Doña Blanca que son dos finqueros que me asesoran en la conformación de esta aplicación.<br />
            Acá les damos una breve introducción.
        </p>
        <p>
            EXDIBO les da la bienvenida a su nueva página web, en la que podrá acceder a todos nuestros servicios y gozar de estos de una forma fácil y rápida y con un solo clic.<br />
            Soy un profesional en la solución de problemas, y la solvencia al problema es esta aplicación web, desarrollada y realizada por el Ingeniero Andrew Anchía González dando estos acabados a la Interfaz de usuario muy limpia y descriptiva para usuario con poco conocimiento en el ambiente tecnológico.<br />
            Otro punto es la accesibilidad al Expediente Digital Bovino que los usuarios estando a nivel nacional como internacional puedan acceder a su información, disponiendo de las últimas tecnologías disponibles en campo tecnologico para proporcionar las últimas y mejores tendencias en cuanto a calidad, seguridad y disponibilidad.<br />
            Así, que espero que todos los usuarios pueden disfrutar de esta aplicación web nueva y que les proporcione un servicio completo del registro y análisis de la información almacenada, ya que podemos acceder al expediente rápidamente, establecer nuevos registros, ver los últimos registros realizados o editar alguno de estos<br />
            Todos los usuarios, pueden conectarse a la aplicación web a través del internet esta nueva sede online que nos permite acceder y dar una respuesta de manera fácil y rápida a todos los usuarios.<br />
            En EXDIBO, somos conscientes de la importancia de estar en constante aseguramiento del servicio y brindar el mejor servicio a nuestros usuarios
            También se pueden realizar solicitudes de cálculo o reportes y resolver cualquier tipo de duda respecto a las decisiones posibles a tomar según lo visto en los reportes y contar con estas herramientas le permite a la finca un mejor rendimiento y toma de decisiones en el manejo de sus animales, recursos, medicamentos o tiempos de retiro.<br />
        </p>
    </div>
</div>

EXDIBO/Views/Expediente/Portada.cshtml
@{
    @using System.Security.Claims;

    ViewData["Title"] = "Portada";
    Layout = "~/Views/Shared/_Layout.cshtml";

    var nameuser = User.FindFirst(ClaimTypes.Name).Value + " " + User.FindFirst(ClaimTypes.UserData).Value;
    var IdUser = User.FindFirst(ClaimTypes.Sid).Value;
}
<link rel="stylesheet" type="text/css" href="~/css/Butons.css" /> 

<div class="align-content-center">
    <h2 class="display-2 text-center" style="font-family:'Liberation Sans'">Expediente Digital Bovino</h2>

    <div class="container-fluid mt-1">
        <div class="row text-start">
            <div class="col m-2 border rounded text-start">
                <h3 class="">Animales </h3>
                <a asp-controller="Animal" asp-action="Animal" class="btn effect01 m-2"><i class="fa-solid fa-cow"></i> Nueva Res</a>
                <br />
                <a asp-controller="Animal" asp-action="ListaAnimales" class="btn effect01 m-2"><i class="fa-solid fa-list-ol"></i><span> Animales</span></a>
                <br />
                <a asp-controller="Animal" asp-action="Production" class="btn effect01 m-2"><i class="fa-solid fa-vial"></i> Producción</a>
                <br />
                <a asp-controller="Animal" asp-action="ListaProduccion" class="btn effect01 m-2"><i class="fa-solid fa-weight-scale"></i> Producciones</a>
                <br />
                <a asp-controller="Animal" asp-action="Ovulation" class="btn effect01 m-2"><i class="fa-solid fa-cow"></i><span> Ovulación</span></a>
                <br />
                <a asp-controller="Animal" asp-action="Gestacion" class="btn effect01 m-2"><i class="fa-solid fa-calendar-check"></i> Gestaci&oacute;n</a>
                
                <br />
                II Etapa
                <br />
                <a class="btn effect01 m-2" asp-controller="Animal" asp-action="Razas"><i class="fa-solid fa-dna"></i> Razas</a>
                <br />
                <a class="btn effect01 m-2" asp-controller="Animal" asp-action="Parto"><i class="fa-solid fa-plus"></i> Parto</a>
               
            </div>

            <div class="col m-2 border rounded">
                <h3 class="">Medicamentos</h3>

                <a class="btn effect01 m-2" asp-controller="Medicamento" asp-action="Farmaco"><i class="fa-solid fa-file-medical"></i> Nueva Medicina</a>
                <br />
                <a class="btn effect01 m-2" asp-controller="Medicamento" asp-action="Farmaceuticos"><i class="fa-solid fa-suitcase-medical"></i> Medicamentos</a>
                <br />
                <a class="btn effect01 m-2"  asp-controller="Medicamento" asp-action="AplicarMedicamento"><i class="fa-solid fa-syringe"></i>  Aplicar Medicamento</a>
                <br />
                <a class="btn effect01 m-2"  asp-controller="Medicamento" asp-action="VerRegistros"><i class="fa-solid fa-folder-tree"></i> Registro Veterinario</a>
                <br />
                II Etapa
                <br />
                <a class="btn effect01 m-2" asp-controller="Medicamento" asp-action="TipoFarmaco"><i class="fa-solid fa-pills"></i> Clasificaci&oacute;n Medicamentos</a>
                <br />
                <a class="btn effect01 m-2" asp-controller="Mantenimiento" asp-action="Enfermedades"><i class="fa-solid fa-plus"></i> Diagnosticos</a>
                 <br />
                <a class="btn effect01 m-2" asp-controller="Mantenimiento" asp-action="Procedimientos"> <i class="fa-solid fa-stethoscope"></i> <i class="fa-solid fa-plus"></i> Procedimientos</a>
                <br />
                <a class="btn effect01 m-2" asp-controller="Mantenimiento" asp-action="Examenes"><i class="fa-solid fa-plus"></i> Examenes</a>
            </div>


            <div class="col m-2 border rounded">

                <h3 class=""> Reportes </h3>

                <a class="btn effect01 m-2" asp-controller="Reporte" asp-action="Nacimientos"><i class="fa-solid fa-file-circle-plus"></i> Nacimientos</a>
                <br />
                <a class="btn effect01 m-2" asp-controller="Reporte" asp-action="AnimalDesecho"><i class="fa-solid fa-file-lines"></i> Desechos Animal</a>
                <br />
                <a class="btn effect01 m-2" asp-controller="Reporte" asp-action="Inyectados"><i class="fa-solid fa-file-prescription"></i> Animales Inyectados</a>
                <br />
                <a class="btn effect01 m-2" asp-controller="Reporte" asp-action="PrenesEfectiva"><i class="fa-solid fa-list-check"></i> Animales en Gestación</a>
                <br />
                <a class="btn effect01 m-2" asp-controller="Reporte" asp-action="Implantado"><i class="fa-solid fa-pallet"></i> Animales Implantados</a>
                <br />
                <a class="btn effect01 m-2" asp-controller="Reporte" asp-action="ProyeccionAlumbramiento"><i class="fa-solid fa-chart-area"></i> Proyección de Alumbramientos</a>
                <br />
                <a class="btn effect01 m-2" asp-controller="Reporte" asp-action="ProduccionLactea"> <i class="fa-solid fa-wine-bottle"></i><i class="fa-solid fa-flask-vial"></i>  Producción L&aacute;ctea</a>
                <br />
                II Etapa
                <br />
                <a class="btn effect01 m-2" asp-controller="Reporte" asp-action="Retiros"><i class="fa-solid fa-plus"></i> Retiro</a>
            </div>

            <div class="col m-2 border rounded">
                <h3 class="">Graficos</h3>
                <a class="btn effect01 m-2" asp-controller="Reporte" asp-action="Gestacion"><i class="fa-solid fa-chart-column"></i> Gestaci&oacute;n Anual</a>
               <br />
                II Etapa
                <br />
                <a class="btn effect01 m-2" asp-controller="Reporte" asp-action="Rendimiento"><i class="fa-solid fa-chart-gantt"></i> Rendimiento Cárnico</a>
                <br />
                <a class="btn effect01 m-2" asp-controller="Reporte" asp-action="TopFarmacos"><i class="fa-solid fa-prescription-bottle-medical"></i> Top Medicamentos</a>
                <br />
                <a class="btn effect01 m-2" asp-controller="Reporte" asp-action="Nacimientos"><i class="fa-solid fa-chart-pie"></i> Proyecci&oacute;n de Nacimientos</a>

            </div>
        </div>

        @*--- OTRO ROW ----*@

        <div class="row mt-2">


            @*---- USUARIOS ---*@

            <div class="col mt-2 border rounded">
                <h3 class=""> Usuarios</h3>

                <a class="btn effect01 m-2" asp-controller="Usuario" asp-action="DetallesUsuario" asp-route-id="@IdUser">  <i class="fa-solid fa-user-doctor"></i> @nameuser</a>

                @if (User.IsInRole("0") || User.IsInRole("1") || User.IsInRole("2"))
                {
                    <a class="btn effect01 m-2" asp-controller="Usuario" asp-action="Nuevo"><i class="fa-solid fa-user-plus"></i> Nuevo Usuario</a>

                    <a class="btn effect01 m-2" asp-controller="Usuario" asp-action="ListaUsuarios"> <i class="fa-solid fa-users-line"></i> Usuarios</a>
                }
                <a class="btn effect01 m-2" asp-controller="Expediente" asp-action="Politicas"> <i class="fa-solid fa-scale-unbalanced"></i> Políticas</a>
            </div>

            @*---- MANTENIMIENTOS ---*@

            <div class="col m-2 border rounded">

                <h3 class=""> Mantenimientos</h3>
                <a class="btn effect01 m-2" asp-controller="Usuario" asp-action="VerRoles"> <i class="fa-solid fa-clipboard-user"></i> Roles</a>
                 <br />
                <a class="btn effect01 m-2"  asp-controller="Mantenimiento" asp-action="Enfermedades"><i class="fa-solid fa-viruses"></i> Enfermedades</a>
                <br />
                <a class="btn effect01 m-2" asp-controller="Expediente" asp-action="Politicas"> <i class="fa-solid fa-scale-unbalanced"></i> Políticas</a>

                <spam>II Etapa</spam>
                <br />
                <a class="btn effect01 m-2" asp-controller="Finca" asp-action="Fincas"><i class="fa-solid fa-map-location"></i> Fincas</a>
                <br />
                <a class="btn effect01 m-2"  asp-controller="Finca" asp-action="Grupos"><i class="fa-solid fa-object-group"></i> Grupos</a>
                <br />
                <a class="btn effect01 m-2"  asp-controller="Mantenimiento" asp-action="Aplicar"><i class="fa-solid fa-eye-dropper"></i> Modo Uso</a>
                <br />
                <a class="btn effect01 m-2"  asp-controller="Mantenimiento" asp-action="Vias"><i class="fa-solid fa-mortar-pestle"></i> Vías</a>
              

            </div>

            <div class="col m-2">
                @*<h3 class=""> Mantenimientos</h3>

                <a asp-controller="" asp-action=""> </a>*@
            </div>

            <div class="col m-2">
                @*<h3 class=""> Mantenimientos</h3>

                <a asp-controller="" asp-action=""> </a>*@
            </div>

        </div>

    </div>
</div>

EXDIBO/Views/Expediente/ProblemasConexion.cshtml
@{
    ViewData["Title"] = "Problemas de Conexión";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div>
    <div class="row">
        <div class="col-6">
                   <img src="~/imagenes/appserve.png" width="80%" height="80%" class="ms-4 rounded"/>
                   <img src="~/imagenes/warning.png" width="90px;" height="90px;" class="m-0"/>   
        </div>
        <div class="col-6">
            <div class="">
                <h1 class="my-4 display-2">Oops, Algo va mal!</h1>
                <h4>Bueno, esto es inesperado...!</h4>
                <h1 class="my-4 display-1">Error 500</h1>
                <h1 class="my-4">Error Interno en el Servidor</h1>
                <p class="mt-5">Intentar volver al Menú</p>
                <a class="btn btn-lg btn-success mt-2" href="javascript: history.go(-1)"><i class="fa-solid fa-arrow-left"></i> Atrás</a>
                <a class="btn btn-lg btn-success mt-2" asp-controller="Expediente" asp-action="Index"><i class="fa-solid fa-house"></i> Inicio</a>
                <a class="btn btn-lg btn-success mt-2" asp-controller="Expediente" asp-action="Portada"><i class="fa-solid fa-bars"></i> Menú</a>
            </div>
        </div>
    </div>
</div>